### PR TITLE
Add support for PROTO message value type.

### PR DESCRIPTION
**Pull request by marcushines**
This change allows the bytes to be a serialized proto message
If the sender uses this encoding it is up to the receiver to
Understand the schema and properly decode the message.

### CODE REVIEW

**Comment by aashaikh** [comment]
I think this is a good addition, but can we make this change along with the overall revisit of the message types?

**Comment by marcushines** [comment]
Small incremental changes ...

On Sep 8, 2016 12:11 PM, "Anees Shaikh" <notifications@github.com> wrote:

I think this is a good addition, but can we make this change along with the
overall revisit of the message types?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openconfig/reference/pull/23#issuecomment-245707336>,
or mute the thread

**Comment by robshakir** [comment]
I don't think that this commit conflicts with other changes that we might want to make here. Suggest that we should merge this change and use something like release tags (or a version number within the proto) to indicate when changes are expected to be stable for implementors.

Merging the individual commits gives us the ability to trace changes back to why more easily IMHO.

**Comment by aashaikh** [comment]
in that case, LGTM

**Comment by tsuna** [comment]
When changing the `.proto` can you make sure to also submit the corresponding changes to the `.pb.go`?

**Pull request merged**
