### PR TITLE
Update gNMI specification doc

### PR DESCRIPTION
**Pull request by aashaikh**
Updates to the spec for version 0.31 of the gNMI service.  Primary changes are:
* updates to describe the TypedValue message to carry data
* replace Error message with gRPC Status message carried in RPC trailer metadata

### CODE REVIEW

**Comment by robshakir** [comment]
PTAL at https://github.com/openconfig/reference/commit/e9239db3096e24bc7ac46b66c62ab02c49036c40 - this is your changes plus some other changes on top. If you're happy with these changes then we can merge that branch into here and then submit.

r.

**Comment by aashaikh** [comment]
done with merge; also proposing to bump version to 0.4.0 given the extent of changes.  PTAL.

**Comment by robshakir** [comment]
Yes, agree that we should bump to 0.4.0. It seemed like it was worth doing all these changes since there were a number of examples that we needed.

Also need to regenerate the generated code in the repo. I'll push these changes.

**Comment by robshakir** [comment]
@aashaikh PTAL, looks like we're ready to merge.

**Comment by robshakir** [comment]
@aashaikh Propose we merge https://github.com/openconfig/reference/tree/gnmi-path-spec-0.4.0 into this branch too - so that we're up-to-date with all documentation for 0.4.0.

**Comment by aashaikh** [comment]
Reviewed and merged the gnmi-path-spec-0.4.0 branch into this one.  Going ahead with merge of overall set of changes.

**Pull request merged**
